# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherCast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherCast
 
  pod 'AlamofireImage', '~> 3.3'
  pod ‘AlamofireObjectMapper’
  pod 'Alamofire', '~> 4.7'


  target 'WeatherCastTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
